// src/components/HistoryGrid.tsx
"use client";

import type { HistoryItem } from "@/lib/types";
import { dbImageFileUrl } from "@/lib/db";
import Icon from "./Icon";

interface HistoryGridProps {
  history: HistoryItem[];
  activeIdx: number;
  onSelect: (idx: number) => void;
  onDelete: (idx: number) => void;
  onClearAll: () => void;
}

const TIME_FMT: Intl.DateTimeFormatOptions = {
  month: "short",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
};

export default function HistoryGrid({
  history,
  activeIdx,
  onSelect,
  onDelete,
  onClearAll,
}: HistoryGridProps) {
  return (
    <>
      <div className="history-bar">
        <h2>
          生成历史
          <span className="history-badge">{history.length} 组</span>
        </h2>
        <button className="btn-danger" type="button" onClick={onClearAll}>
          <Icon name="trash" />
          <span>清空</span>
        </button>
      </div>
      <div className="history-grid">
        {history.length === 0 ? (
          <div className="empty">还没有商品详情图历史</div>
        ) : (
          history
            .map((item, idx) => ({ item, idx }))
            .reverse()
            .map(({ item, idx }) => {
              const cover = item.prompts.find((prompt) => prompt.base64 || prompt.imageId);
              const coverSrc = cover?.base64
                ? "data:image/png;base64," + cover.base64
                : cover?.imageId
                  ? dbImageFileUrl(cover.imageId)
                  : null;
              const done = item.prompts.filter((prompt) => prompt.base64 || prompt.imageId).length;
              const time = new Date(item.timestamp).toLocaleString("zh-CN", TIME_FMT);
              const promptPreview = item.prompts
                .slice(0, 2)
                .map((prompt) => prompt.title)
                .join(" / ");
              const generationMeta = item.generation
                ? `${item.generation.aspectRatio ?? "Auto"} · ${item.generation.quality ?? "1K"}`
                : "默认参数";
              return (
                <div
                  key={item.id ?? `history-${idx}-${item.timestamp}`}
                  className={"history-card" + (idx === activeIdx ? " is-active" : "")}
                  onClick={() => onSelect(idx)}
                >
                  <div className="history-cover">
                    <span className="tile-no">{done}/{item.prompts.length}</span>
                    {coverSrc ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={coverSrc} alt={item.product.name} />
                    ) : (
                      <div className="tile-empty">{item.product.name.slice(0, 8)}</div>
                    )}
                  </div>
                  <div className="history-card-body">
                    <strong title={item.product.name}>{item.product.name}</strong>
                    <p title={item.product.sellingPoints}>{item.product.sellingPoints}</p>
                    <small title={promptPreview}>{promptPreview || "暂无详情图文案"}</small>
                    <span className="history-meta-pill">{generationMeta}</span>
                  </div>
                  <div className="history-card-foot">
                    <span>{time}</span>
                    <button
                      className="tile-del"
                      type="button"
                      title="删除"
                      onClick={(event) => {
                        event.stopPropagation();
                        onDelete(idx);
                      }}
                    >
                      <Icon name="trash" />
                    </button>
                  </div>
                </div>
              );
            })
        )}
      </div>
    </>
  );
}

// app/components/HistoryGrid.vue
<script setup lang="ts">
import { dbImageFileUrl } from "@/lib/db"
import type { DetailPromptItem, HistoryItem } from "@/lib/types"
import Icon from "./Icon.vue"

defineProps<{
  history: HistoryItem[]
  activeIdx: number
}>()

const emit = defineEmits<{
  select: [idx: number]
  delete: [idx: number]
  clearAll: []
}>()

const TIME_FMT: Intl.DateTimeFormatOptions = {
  month: "short",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
}

function getPromptSrc(prompt: DetailPromptItem | undefined) {
  if (!prompt) return null
  if (prompt.base64) return `data:image/png;base64,${prompt.base64}`
  if (prompt.imageId) return dbImageFileUrl(prompt.imageId)
  return null
}

function getReversed(history: HistoryItem[]) {
  return history.map((item, idx) => ({ item, idx })).reverse()
}
</script>

<template>
  <div class="history-bar">
    <h2>
      生成历史
      <span class="history-badge">{{ history.length }} 组</span>
    </h2>
    <button class="btn-danger" type="button" @click="emit('clearAll')">
      <Icon name="trash" />
      <span>清空</span>
    </button>
  </div>
  <div class="history-grid">
    <div v-if="history.length === 0" class="empty">还没有商品详情图历史</div>
    <div
      v-for="{ item, idx } in getReversed(history)"
      v-else
      :key="item.id ?? `history-${idx}-${item.timestamp}`"
      :class="['history-card', { 'is-active': idx === activeIdx }]"
      @click="emit('select', idx)"
    >
      <div class="history-cover">
        <span class="tile-no">
          {{ item.prompts.filter((prompt) => prompt.base64 || prompt.imageId).length }}/{{ item.prompts.length }}
        </span>
        <img
          v-if="getPromptSrc(item.prompts.find((prompt) => prompt.base64 || prompt.imageId))"
          :src="getPromptSrc(item.prompts.find((prompt) => prompt.base64 || prompt.imageId))!"
          :alt="item.product.name"
        >
        <div v-else class="tile-empty">{{ item.product.name.slice(0, 8) }}</div>
      </div>
      <div class="history-card-body">
        <strong :title="item.product.name">{{ item.product.name }}</strong>
        <p :title="item.product.sellingPoints">{{ item.product.sellingPoints }}</p>
        <small :title="item.prompts.slice(0, 2).map((prompt) => prompt.title).join(' / ')">
          {{ item.prompts.slice(0, 2).map((prompt) => prompt.title).join(" / ") || "暂无详情图文案" }}
        </small>
        <span class="history-meta-pill">
          {{
            item.generation
              ? `${item.generation.aspectRatio ?? "Auto"} · ${item.generation.quality ?? "1K"}`
              : "默认参数"
          }}
        </span>
      </div>
      <div class="history-card-foot">
        <span>{{ new Date(item.timestamp).toLocaleString("zh-CN", TIME_FMT) }}</span>
        <button
          class="tile-del"
          type="button"
          title="删除"
          @click.stop="emit('delete', idx)"
        >
          <Icon name="trash" />
        </button>
      </div>
    </div>
  </div>
</template>
