// src/components/QualitySelector.tsx
"use client";

import { IMAGE_QUALITY_OPTIONS } from "@/lib/imageOptions";
import type { ImageQuality } from "@/lib/types";
import SegmentedControl from "./SegmentedControl";

export default function QualitySelector({
  value,
  onChange,
  disabled,
}: {
  value: ImageQuality;
  onChange: (value: ImageQuality) => void;
  disabled?: boolean;
}) {
  return (
    <SegmentedControl
      ariaLabel="清晰度"
      value={value}
      options={IMAGE_QUALITY_OPTIONS}
      onChange={onChange}
      disabled={disabled}
      className="quality-segments"
    />
  );
}

// app/components/QualitySelector.vue
<script setup lang="ts">
import { IMAGE_QUALITY_OPTIONS } from "@/lib/imageOptions"
import type { ImageQuality } from "@/lib/types"
import SegmentedControl from "./SegmentedControl.vue"

withDefaults(defineProps<{
  value: ImageQuality
  disabled?: boolean
}>(), {
  disabled: false,
})

const emit = defineEmits<{
  change: [value: ImageQuality]
}>()
</script>

<template>
  <SegmentedControl
    aria-label="清晰度"
    ariaLabel="清晰度"
    :value="value"
    :options="IMAGE_QUALITY_OPTIONS"
    :disabled="disabled"
    class-name="quality-segments"
    @change="emit('change', $event as ImageQuality)"
  />
</template>
