// src/components/SegmentedControl.tsx
"use client";

interface SegmentedOption<T extends string> {
  label: string;
  value: T;
}

interface SegmentedControlProps<T extends string> {
  value: T;
  options: Array<SegmentedOption<T>>;
  onChange: (value: T) => void;
  ariaLabel: string;
  disabled?: boolean;
  className?: string;
}

export default function SegmentedControl<T extends string>({
  value,
  options,
  onChange,
  ariaLabel,
  disabled = false,
  className,
}: SegmentedControlProps<T>) {
  return (
    <div
      className={`segmented-control${className ? ` ${className}` : ""}`}
      role="radiogroup"
      aria-label={ariaLabel}
    >
      {options.map((option) => {
        const active = option.value === value;
        return (
          <button
            key={option.value}
            type="button"
            role="radio"
            aria-checked={active}
            className={`segment-option${active ? " is-active" : ""}`}
            disabled={disabled}
            onClick={() => onChange(option.value)}
          >
            {option.label}
          </button>
        );
      })}
    </div>
  );
}

// app/components/SegmentedControl.vue
<script setup lang="ts" generic="T extends string">
interface SegmentedOption<T extends string> {
  label: string
  value: T
}

withDefaults(defineProps<{
  value: T
  options: Array<SegmentedOption<T>>
  ariaLabel: string
  disabled?: boolean
  className?: string
}>(), {
  disabled: false,
  className: "",
})

const emit = defineEmits<{
  change: [value: T]
}>()
</script>

<template>
  <div
    :class="['segmented-control', className]"
    role="radiogroup"
    :aria-label="ariaLabel"
  >
    <button
      v-for="option in options"
      :key="option.value"
      type="button"
      role="radio"
      :aria-checked="option.value === value"
      :class="['segment-option', { 'is-active': option.value === value }]"
      :disabled="disabled"
      @click="emit('change', option.value)"
    >
      {{ option.label }}
    </button>
  </div>
</template>
