// app/components/Stage.vue
<script setup lang="ts">
import { computed } from "vue"
import { dbImageFileUrl } from "@/lib/db"
import type { DetailPromptItem } from "@/lib/types"
import Icon from "./Icon.vue"

const props = defineProps<{
  prompts: DetailPromptItem[]
  activeIndex: number
  busy: boolean
}>()

const emit = defineEmits<{
  select: [index: number]
  download: [index: number]
  zoom: [index: number]
}>()

const active = computed(() => props.prompts[props.activeIndex] ?? null)
const activeSrc = computed(() => {
  if (!active.value) return null
  if (active.value.imageId) return dbImageFileUrl(active.value.imageId)
  return null
})

function getItemSrc(item: DetailPromptItem) {
  if (item.imageId) return dbImageFileUrl(item.imageId)
  return null
}
</script>

<template>
  <div v-if="!prompts.length" class="stage">
    <div class="stage-empty-card">
      <Icon name="image" class="icon-large" />
      <div class="icon-hint">您的商品详情图将在这里呈现</div>
      <p class="empty-tip">先填写商品资料并生成方案，然后点击"批量生成详情图"</p>
    </div>
  </div>

  <div v-else class="detail-stage">
    <div class="stage-main">
      <template v-if="activeSrc">
        <img :src="activeSrc" :alt="active?.title ?? ''" @click="emit('zoom', activeIndex)">
        <div class="stage-caption">{{ active?.title }}</div>
        <div class="stage-actions">
          <button class="btn-ghost" type="button" @click="emit('download', activeIndex)">
            <Icon name="download" />
            <span>下载</span>
          </button>
          <button class="btn-ghost" type="button" @click="emit('zoom', activeIndex)">
            <Icon name="zoom" />
            <span>预览</span>
          </button>
        </div>
      </template>

      <div v-else class="stage-placeholder">
        <template v-if="busy && (active?.status === 'running' || active?.status === 'queued')">
          <div class="spinner" />
          <div class="loading-hint">正在生成：{{ active?.title }}</div>
          <p class="loading-progress">预计需要 15-30 秒，请稍候...</p>
        </template>
        <template v-else-if="active?.status === 'failed'">
          <Icon name="warning" class="icon-large" />
          <div class="alert">{{ active.error || "生成失败" }}</div>
        </template>
        <template v-else>
          <Icon name="queue" class="icon-large" />
          <div class="icon-hint">等待生成：{{ active?.title }}</div>
        </template>
      </div>
    </div>

    <div class="result-strip" aria-label="详情图生成结果">
      <button
        v-for="(item, index) in prompts"
        :key="item.id"
        type="button"
        :class="['result-thumb', { 'is-active': index === activeIndex }]"
        @click="emit('select', index)"
      >
        <span :class="['status-dot', `is-${item.status}`]" />
        <img v-if="getItemSrc(item)" :src="getItemSrc(item)!" :alt="item.title">
        <span v-else class="result-thumb-empty">{{ index + 1 }}</span>
      </button>
    </div>
  </div>
</template>

// src/components/Stage.tsx
"use client";

import type { DetailPromptItem } from "@/lib/types";
import { dbImageFileUrl } from "@/lib/db";
import Icon from "./Icon";

interface StageProps {
  prompts: DetailPromptItem[];
  activeIndex: number;
  busy: boolean;
  onSelect: (index: number) => void;
  onDownload: (index: number) => void;
  onZoom: (index: number) => void;
}

export default function Stage({
  prompts,
  activeIndex,
  busy,
  onSelect,
  onDownload,
  onZoom,
}: StageProps) {
  const active = prompts[activeIndex] ?? null;
  const activeSrc = active?.base64
    ? "data:image/png;base64," + active.base64
    : active?.imageId
      ? dbImageFileUrl(active.imageId)
      : null;

  if (!prompts.length) {
    return (
      <div className="stage">
        <div className="stage-empty-card">
          <Icon name="image" className="icon-large" />
          <div className="icon-hint">商品详情图将在这里逐张生成</div>
        </div>
      </div>
    );
  }

  return (
    <div className="detail-stage">
      <div className="stage-main">
        {activeSrc ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={activeSrc}
              alt={active?.title ?? ""}
              onClick={() => onZoom(activeIndex)}
            />
            <div className="stage-caption">{active?.title}</div>
            <div className="stage-actions">
              <button className="btn-ghost" type="button" onClick={() => onDownload(activeIndex)}>
                <Icon name="download" />
                <span>下载</span>
              </button>
              <button className="btn-ghost" type="button" onClick={() => onZoom(activeIndex)}>
                <Icon name="zoom" />
                <span>预览</span>
              </button>
            </div>
          </>
        ) : (
          <div className="stage-placeholder">
            {busy && (active?.status === "running" || active?.status === "queued") ? (
              <>
                <div className="spinner" />
                <div className="loading-hint">正在生成：{active?.title}</div>
              </>
            ) : active?.status === "failed" ? (
              <>
                <Icon name="warning" className="icon-large" />
                <div className="alert">{active.error || "生成失败"}</div>
              </>
            ) : (
              <>
                <Icon name="queue" className="icon-large" />
                <div className="icon-hint">等待生成：{active?.title}</div>
              </>
            )}
          </div>
        )}
      </div>

      <div className="result-strip" aria-label="详情图生成结果">
        {prompts.map((item, index) => {
          const itemSrc = item.base64
            ? "data:image/png;base64," + item.base64
            : item.imageId
              ? dbImageFileUrl(item.imageId)
              : null;
          return (
            <button
              key={item.id}
              type="button"
              className={`result-thumb${index === activeIndex ? " is-active" : ""}`}
              onClick={() => onSelect(index)}
            >
              <span className={`status-dot is-${item.status}`} />
              {itemSrc ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={itemSrc} alt={item.title} />
              ) : (
                <span className="result-thumb-empty">{index + 1}</span>
              )}
            </button>
          );
        })}
      </div>
    </div>
  );
}
